apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
spec:
  type: NodePort
  selector:
    app: cadvisor
  ports:
  - port: 8080   # Port exposed by cAdvisor
    targetPort: 8080
    nodePort: 32000  # Expose on a specific NodePort (adjust as needed)
