apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-app-health
  name: lb3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mahesh-app-health
  type: NodePort
status:
  loadBalancer: {}
