apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mahesh-adminer
  name: mahesh-adminer-lb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: mahesh-adminer
  type: NodePort
status:
  loadBalancer: {}
