apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mahesh-app
  name: maheshlb1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: mahesh-app
  type: NodePort
status:
  loadBalancer: {}
