apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-mon
  name: lb1
spec:
  ports:
  - port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: mahesh-mon
  type: NodePort
status:
  loadBalancer: {}
