apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-webapp
  name: mahesh-webapp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mahesh-webapp
  type: NodePort
status:
  loadBalancer: {}
