apiVersion: v1
kind: Namespace
metadata:
  name: maheshk8s1

---
apiVersion: v1
kind: Pod
metadata:
  namespace: maheshk8s1
  creationTimestamp: null
  labels:
    run: mahesh-ubuntu-pod
  name: mahesh-ubuntu-pod
spec:
  containers:
  - image: ubuntu:latest
    name: mahesh-ubuntu-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


---

apiVersion: v1
kind: Service
metadata:
  namespace: maheshk8s1
  creationTimestamp: null
  labels:
    app: mahesh-service-nodeport-svc1
  name: mahesh-service-nodeport-svc1
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector: # pod finder using pod label
    app: mahesh-app
  type: NodePort
status:
  loadBalancer: {}

