apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: mahesh-assignment-day8
  name: maheshlb
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: mahesh-assignment-day8
  type: NodePort
status:
  loadBalancer: {}
