apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-dep
  name: mahesh-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mahesh-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mahesh-dep
    spec:
      volumes:
      - name: mahesh-db-volx1
        persistentVolumeClaim:
          claimName: mahesh-cliam-new2
      containers:
      - image: mysql:8.0
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: RootPass@123
        volumeMounts:
        - name: mahesh-db-volx1
          mountPath: /var/lib/mysql/
status: {}
