apiVersion: v1
kind: PersistentVolume
metadata:
  name: mahesh-pv
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/db-store/mahesh/
    server: 172.31.9.111