apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mahesh-cliam-new2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual 