apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-mongo
  name: mahesh-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mahesh-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mahesh-mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources: 
          requests:
            memory: 400M
            cpu: 200m
          limits: 
            memory: 2G
            cpu: 700m
        envFrom:
        - secretRef:
            name: mahesh-mongo-cred
status: {}
