apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-react-app
  name: maheshlb1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mahesh-react-app
  type: NodePort
status:
  loadBalancer: {}
