apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-db
  name: mahesh-db-lb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mahesh-db
  type: ClusterIP
status:
  loadBalancer: {}
