apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: maheshwebapp
  name: maheshwebapp
spec:
  nodeName: node2
  containers:
  - image: httpd:latest
    name: maheshwebapp
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
