apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mahesh-app
  name: mahesh-app
spec:
  imagePullSecrets:
  - name: mahesh-reg-cred
  containers:
  - image: cloud4c.azurecr.io/day7app:uiv1
    name: mahesh-app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
