apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashu-db
  name: ashu-db
spec:
  containers:
  - image: mysql
    name: ashu-db
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
