apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-secure-app
  name: s1
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: mahesh-secure-app
  type: NodePort
status:
  loadBalancer: {}
