apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: maheshadminerpod
  name: maheshadminerpod
spec:
  nodeName: node3
  containers:
  - image: adminer:4.8.1
    name: maheshadminerpod
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
