apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mahesh-app
  name: mahesh-app
spec:
  containers:
  - image: docker.io/maheshc4c/nodeapp:v1
    name: mahesh-app
    ports:
    - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
