apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mahesh-ui-pod
  name: mahesh-ui-pod
spec:
  containers:
  - image: nginx:1.24
    name: mahesh-ui-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
