apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mahesh-webapp
  name: maheshlb1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mahesh-webapp
  type: NodePort
status:
  loadBalancer: {}
